/*
 *     Copyright (c) 2018-2019, NVIDIA CORPORATION.  All rights reserved.
 *
 * NVIDIA CORPORATION and its licensors retain all intellectual property
 * and proprietary rights in and to this software, related documentation
 * and any modifications thereto.  Any use, reproduction, disclosure or
 * distribution of this software and related documentation without an express
 * license agreement from NVIDIA CORPORATION is strictly prohibited.
 *
 */


/*
 *
 * WARNING - this file is automatically generated. DO NOT EDIT.
 *
 */

#include "mth_intrinsics.h"
#include "mth_tbldefs.h"
#include <complex.h>



vrd8_t
__gd_acos_8_f(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_acos][sv_ds][frp_f];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_asin_8_f(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_asin][sv_ds][frp_f];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_atan_8_f(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_atan][sv_ds][frp_f];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_atan2_8_f(vrd8_t x, vrd8_t y)
{
  double (*fptr)(double, double);
  fptr = (double(*)(double, double))MTH_DISPATCH_TBL[func_atan2][sv_ds][frp_f];
  return __ZGVzN8vv__mth_i_vr8vr8( x, y, fptr);
}

vrd8_t
__gd_cos_8_f(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_cos][sv_ds][frp_f];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_sin_8_f(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_sin][sv_ds][frp_f];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_tan_8_f(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_tan][sv_ds][frp_f];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_cosh_8_f(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_cosh][sv_ds][frp_f];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_sinh_8_f(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_sinh][sv_ds][frp_f];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_tanh_8_f(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_tanh][sv_ds][frp_f];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_exp_8_f(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_exp][sv_ds][frp_f];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_log_8_f(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_log][sv_ds][frp_f];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_log10_8_f(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_log10][sv_ds][frp_f];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_pow_8_f(vrd8_t x, vrd8_t y)
{
  double (*fptr)(double, double);
  fptr = (double(*)(double, double))MTH_DISPATCH_TBL[func_pow][sv_ds][frp_f];
  return __ZGVzN8vv__mth_i_vr8vr8( x, y, fptr);
}

vrd8_t
__gd_div_8_f(vrd8_t x, vrd8_t y)
{
  double (*fptr)(double, double);
  fptr = (double(*)(double, double))MTH_DISPATCH_TBL[func_div][sv_ds][frp_f];
  return __ZGVzN8vv__mth_i_vr8vr8( x, y, fptr);
}

vrd8_t
__gd_sqrt_8_f(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_sqrt][sv_ds][frp_f];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_mod_8_f(vrd8_t x, vrd8_t y)
{
  double (*fptr)(double, double);
  fptr = (double(*)(double, double))MTH_DISPATCH_TBL[func_mod][sv_ds][frp_f];
  return __ZGVzN8vv__mth_i_vr8vr8( x, y, fptr);
}

vrd8_t
__gd_aint_8_f(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_aint][sv_ds][frp_f];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_ceil_8_f(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_ceil][sv_ds][frp_f];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_floor_8_f(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_floor][sv_ds][frp_f];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrs16_t
__gs_acos_16_f(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_acos][sv_ss][frp_f];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_asin_16_f(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_asin][sv_ss][frp_f];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_atan_16_f(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_atan][sv_ss][frp_f];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_atan2_16_f(vrs16_t x, vrs16_t y)
{
  float (*fptr)(float, float);
  fptr = (float(*)(float, float))MTH_DISPATCH_TBL[func_atan2][sv_ss][frp_f];
  return __ZGVzN16vv__mth_i_vr4vr4( x, y, fptr);
}

vrs16_t
__gs_cos_16_f(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_cos][sv_ss][frp_f];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_sin_16_f(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_sin][sv_ss][frp_f];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_tan_16_f(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_tan][sv_ss][frp_f];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_cosh_16_f(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_cosh][sv_ss][frp_f];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_sinh_16_f(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_sinh][sv_ss][frp_f];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_tanh_16_f(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_tanh][sv_ss][frp_f];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_exp_16_f(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_exp][sv_ss][frp_f];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_log_16_f(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_log][sv_ss][frp_f];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_log10_16_f(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_log10][sv_ss][frp_f];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_pow_16_f(vrs16_t x, vrs16_t y)
{
  float (*fptr)(float, float);
  fptr = (float(*)(float, float))MTH_DISPATCH_TBL[func_pow][sv_ss][frp_f];
  return __ZGVzN16vv__mth_i_vr4vr4( x, y, fptr);
}

vrs16_t
__gs_div_16_f(vrs16_t x, vrs16_t y)
{
  float (*fptr)(float, float);
  fptr = (float(*)(float, float))MTH_DISPATCH_TBL[func_div][sv_ss][frp_f];
  return __ZGVzN16vv__mth_i_vr4vr4( x, y, fptr);
}

vrs16_t
__gs_sqrt_16_f(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_sqrt][sv_ss][frp_f];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_mod_16_f(vrs16_t x, vrs16_t y)
{
  float (*fptr)(float, float);
  fptr = (float(*)(float, float))MTH_DISPATCH_TBL[func_mod][sv_ss][frp_f];
  return __ZGVzN16vv__mth_i_vr4vr4( x, y, fptr);
}

vrs16_t
__gs_aint_16_f(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_aint][sv_ss][frp_f];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_ceil_16_f(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_ceil][sv_ss][frp_f];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_floor_16_f(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_floor][sv_ss][frp_f];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vcd4_t
__gz_acos_4_f(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_acos][sv_zs][frp_f];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_asin_4_f(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_asin][sv_zs][frp_f];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_atan_4_f(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_atan][sv_zs][frp_f];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_atan2_4_f(vcd4_t x, vcd4_t y)
{
  double _Complex (*fptr)(double _Complex, double _Complex);
  fptr = (double _Complex(*)(double _Complex, double _Complex))MTH_DISPATCH_TBL[func_atan2][sv_zs][frp_f];
  return __ZGVzN4vv__mth_i_vc8vc8( x, y, fptr);
}

vcd4_t
__gz_cos_4_f(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_cos][sv_zs][frp_f];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_sin_4_f(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_sin][sv_zs][frp_f];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_tan_4_f(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_tan][sv_zs][frp_f];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_cosh_4_f(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_cosh][sv_zs][frp_f];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_sinh_4_f(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_sinh][sv_zs][frp_f];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_tanh_4_f(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_tanh][sv_zs][frp_f];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_exp_4_f(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_exp][sv_zs][frp_f];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_log_4_f(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_log][sv_zs][frp_f];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_log10_4_f(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_log10][sv_zs][frp_f];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_pow_4_f(vcd4_t x, vcd4_t y)
{
  double _Complex (*fptr)(double _Complex, double _Complex);
  fptr = (double _Complex(*)(double _Complex, double _Complex))MTH_DISPATCH_TBL[func_pow][sv_zs][frp_f];
  return __ZGVzN4vv__mth_i_vc8vc8( x, y, fptr);
}

vcd4_t
__gz_div_4_f(vcd4_t x, vcd4_t y)
{
  double _Complex (*fptr)(double _Complex, double _Complex);
  fptr = (double _Complex(*)(double _Complex, double _Complex))MTH_DISPATCH_TBL[func_div][sv_zs][frp_f];
  return __ZGVzN4vv__mth_i_vc8vc8( x, y, fptr);
}

vcd4_t
__gz_sqrt_4_f(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_sqrt][sv_zs][frp_f];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_mod_4_f(vcd4_t x, vcd4_t y)
{
  double _Complex (*fptr)(double _Complex, double _Complex);
  fptr = (double _Complex(*)(double _Complex, double _Complex))MTH_DISPATCH_TBL[func_mod][sv_zs][frp_f];
  return __ZGVzN4vv__mth_i_vc8vc8( x, y, fptr);
}

vcd4_t
__gz_aint_4_f(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_aint][sv_zs][frp_f];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_ceil_4_f(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_ceil][sv_zs][frp_f];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_floor_4_f(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_floor][sv_zs][frp_f];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcs8_t
__gc_acos_8_f(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_acos][sv_cs][frp_f];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_asin_8_f(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_asin][sv_cs][frp_f];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_atan_8_f(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_atan][sv_cs][frp_f];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_atan2_8_f(vcs8_t x, vcs8_t y)
{
  float _Complex (*fptr)(float _Complex, float _Complex);
  fptr = (float _Complex(*)(float _Complex, float _Complex))MTH_DISPATCH_TBL[func_atan2][sv_cs][frp_f];
  return __ZGVzN8vv__mth_i_vc4vc4( x, y, fptr);
}

vcs8_t
__gc_cos_8_f(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_cos][sv_cs][frp_f];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_sin_8_f(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_sin][sv_cs][frp_f];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_tan_8_f(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_tan][sv_cs][frp_f];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_cosh_8_f(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_cosh][sv_cs][frp_f];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_sinh_8_f(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_sinh][sv_cs][frp_f];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_tanh_8_f(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_tanh][sv_cs][frp_f];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_exp_8_f(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_exp][sv_cs][frp_f];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_log_8_f(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_log][sv_cs][frp_f];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_log10_8_f(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_log10][sv_cs][frp_f];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_pow_8_f(vcs8_t x, vcs8_t y)
{
  float _Complex (*fptr)(float _Complex, float _Complex);
  fptr = (float _Complex(*)(float _Complex, float _Complex))MTH_DISPATCH_TBL[func_pow][sv_cs][frp_f];
  return __ZGVzN8vv__mth_i_vc4vc4( x, y, fptr);
}

vcs8_t
__gc_div_8_f(vcs8_t x, vcs8_t y)
{
  float _Complex (*fptr)(float _Complex, float _Complex);
  fptr = (float _Complex(*)(float _Complex, float _Complex))MTH_DISPATCH_TBL[func_div][sv_cs][frp_f];
  return __ZGVzN8vv__mth_i_vc4vc4( x, y, fptr);
}

vcs8_t
__gc_sqrt_8_f(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_sqrt][sv_cs][frp_f];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_mod_8_f(vcs8_t x, vcs8_t y)
{
  float _Complex (*fptr)(float _Complex, float _Complex);
  fptr = (float _Complex(*)(float _Complex, float _Complex))MTH_DISPATCH_TBL[func_mod][sv_cs][frp_f];
  return __ZGVzN8vv__mth_i_vc4vc4( x, y, fptr);
}

vcs8_t
__gc_aint_8_f(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_aint][sv_cs][frp_f];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_ceil_8_f(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_ceil][sv_cs][frp_f];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_floor_8_f(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_floor][sv_cs][frp_f];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vrd8_t
__gd_acos_8_p(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_acos][sv_ds][frp_p];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_asin_8_p(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_asin][sv_ds][frp_p];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_atan_8_p(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_atan][sv_ds][frp_p];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_atan2_8_p(vrd8_t x, vrd8_t y)
{
  double (*fptr)(double, double);
  fptr = (double(*)(double, double))MTH_DISPATCH_TBL[func_atan2][sv_ds][frp_p];
  return __ZGVzN8vv__mth_i_vr8vr8( x, y, fptr);
}

vrd8_t
__gd_cos_8_p(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_cos][sv_ds][frp_p];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_sin_8_p(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_sin][sv_ds][frp_p];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_tan_8_p(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_tan][sv_ds][frp_p];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_cosh_8_p(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_cosh][sv_ds][frp_p];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_sinh_8_p(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_sinh][sv_ds][frp_p];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_tanh_8_p(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_tanh][sv_ds][frp_p];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_exp_8_p(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_exp][sv_ds][frp_p];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_log_8_p(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_log][sv_ds][frp_p];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_log10_8_p(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_log10][sv_ds][frp_p];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_pow_8_p(vrd8_t x, vrd8_t y)
{
  double (*fptr)(double, double);
  fptr = (double(*)(double, double))MTH_DISPATCH_TBL[func_pow][sv_ds][frp_p];
  return __ZGVzN8vv__mth_i_vr8vr8( x, y, fptr);
}

vrd8_t
__gd_div_8_p(vrd8_t x, vrd8_t y)
{
  double (*fptr)(double, double);
  fptr = (double(*)(double, double))MTH_DISPATCH_TBL[func_div][sv_ds][frp_p];
  return __ZGVzN8vv__mth_i_vr8vr8( x, y, fptr);
}

vrd8_t
__gd_sqrt_8_p(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_sqrt][sv_ds][frp_p];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_mod_8_p(vrd8_t x, vrd8_t y)
{
  double (*fptr)(double, double);
  fptr = (double(*)(double, double))MTH_DISPATCH_TBL[func_mod][sv_ds][frp_p];
  return __ZGVzN8vv__mth_i_vr8vr8( x, y, fptr);
}

vrd8_t
__gd_aint_8_p(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_aint][sv_ds][frp_p];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_ceil_8_p(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_ceil][sv_ds][frp_p];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_floor_8_p(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_floor][sv_ds][frp_p];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrs16_t
__gs_acos_16_p(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_acos][sv_ss][frp_p];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_asin_16_p(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_asin][sv_ss][frp_p];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_atan_16_p(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_atan][sv_ss][frp_p];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_atan2_16_p(vrs16_t x, vrs16_t y)
{
  float (*fptr)(float, float);
  fptr = (float(*)(float, float))MTH_DISPATCH_TBL[func_atan2][sv_ss][frp_p];
  return __ZGVzN16vv__mth_i_vr4vr4( x, y, fptr);
}

vrs16_t
__gs_cos_16_p(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_cos][sv_ss][frp_p];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_sin_16_p(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_sin][sv_ss][frp_p];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_tan_16_p(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_tan][sv_ss][frp_p];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_cosh_16_p(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_cosh][sv_ss][frp_p];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_sinh_16_p(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_sinh][sv_ss][frp_p];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_tanh_16_p(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_tanh][sv_ss][frp_p];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_exp_16_p(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_exp][sv_ss][frp_p];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_log_16_p(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_log][sv_ss][frp_p];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_log10_16_p(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_log10][sv_ss][frp_p];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_pow_16_p(vrs16_t x, vrs16_t y)
{
  float (*fptr)(float, float);
  fptr = (float(*)(float, float))MTH_DISPATCH_TBL[func_pow][sv_ss][frp_p];
  return __ZGVzN16vv__mth_i_vr4vr4( x, y, fptr);
}

vrs16_t
__gs_div_16_p(vrs16_t x, vrs16_t y)
{
  float (*fptr)(float, float);
  fptr = (float(*)(float, float))MTH_DISPATCH_TBL[func_div][sv_ss][frp_p];
  return __ZGVzN16vv__mth_i_vr4vr4( x, y, fptr);
}

vrs16_t
__gs_sqrt_16_p(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_sqrt][sv_ss][frp_p];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_mod_16_p(vrs16_t x, vrs16_t y)
{
  float (*fptr)(float, float);
  fptr = (float(*)(float, float))MTH_DISPATCH_TBL[func_mod][sv_ss][frp_p];
  return __ZGVzN16vv__mth_i_vr4vr4( x, y, fptr);
}

vrs16_t
__gs_aint_16_p(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_aint][sv_ss][frp_p];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_ceil_16_p(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_ceil][sv_ss][frp_p];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_floor_16_p(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_floor][sv_ss][frp_p];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vcd4_t
__gz_acos_4_p(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_acos][sv_zs][frp_p];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_asin_4_p(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_asin][sv_zs][frp_p];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_atan_4_p(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_atan][sv_zs][frp_p];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_atan2_4_p(vcd4_t x, vcd4_t y)
{
  double _Complex (*fptr)(double _Complex, double _Complex);
  fptr = (double _Complex(*)(double _Complex, double _Complex))MTH_DISPATCH_TBL[func_atan2][sv_zs][frp_p];
  return __ZGVzN4vv__mth_i_vc8vc8( x, y, fptr);
}

vcd4_t
__gz_cos_4_p(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_cos][sv_zs][frp_p];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_sin_4_p(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_sin][sv_zs][frp_p];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_tan_4_p(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_tan][sv_zs][frp_p];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_cosh_4_p(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_cosh][sv_zs][frp_p];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_sinh_4_p(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_sinh][sv_zs][frp_p];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_tanh_4_p(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_tanh][sv_zs][frp_p];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_exp_4_p(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_exp][sv_zs][frp_p];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_log_4_p(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_log][sv_zs][frp_p];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_log10_4_p(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_log10][sv_zs][frp_p];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_pow_4_p(vcd4_t x, vcd4_t y)
{
  double _Complex (*fptr)(double _Complex, double _Complex);
  fptr = (double _Complex(*)(double _Complex, double _Complex))MTH_DISPATCH_TBL[func_pow][sv_zs][frp_p];
  return __ZGVzN4vv__mth_i_vc8vc8( x, y, fptr);
}

vcd4_t
__gz_div_4_p(vcd4_t x, vcd4_t y)
{
  double _Complex (*fptr)(double _Complex, double _Complex);
  fptr = (double _Complex(*)(double _Complex, double _Complex))MTH_DISPATCH_TBL[func_div][sv_zs][frp_p];
  return __ZGVzN4vv__mth_i_vc8vc8( x, y, fptr);
}

vcd4_t
__gz_sqrt_4_p(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_sqrt][sv_zs][frp_p];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_mod_4_p(vcd4_t x, vcd4_t y)
{
  double _Complex (*fptr)(double _Complex, double _Complex);
  fptr = (double _Complex(*)(double _Complex, double _Complex))MTH_DISPATCH_TBL[func_mod][sv_zs][frp_p];
  return __ZGVzN4vv__mth_i_vc8vc8( x, y, fptr);
}

vcd4_t
__gz_aint_4_p(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_aint][sv_zs][frp_p];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_ceil_4_p(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_ceil][sv_zs][frp_p];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_floor_4_p(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_floor][sv_zs][frp_p];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcs8_t
__gc_acos_8_p(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_acos][sv_cs][frp_p];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_asin_8_p(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_asin][sv_cs][frp_p];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_atan_8_p(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_atan][sv_cs][frp_p];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_atan2_8_p(vcs8_t x, vcs8_t y)
{
  float _Complex (*fptr)(float _Complex, float _Complex);
  fptr = (float _Complex(*)(float _Complex, float _Complex))MTH_DISPATCH_TBL[func_atan2][sv_cs][frp_p];
  return __ZGVzN8vv__mth_i_vc4vc4( x, y, fptr);
}

vcs8_t
__gc_cos_8_p(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_cos][sv_cs][frp_p];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_sin_8_p(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_sin][sv_cs][frp_p];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_tan_8_p(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_tan][sv_cs][frp_p];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_cosh_8_p(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_cosh][sv_cs][frp_p];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_sinh_8_p(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_sinh][sv_cs][frp_p];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_tanh_8_p(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_tanh][sv_cs][frp_p];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_exp_8_p(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_exp][sv_cs][frp_p];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_log_8_p(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_log][sv_cs][frp_p];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_log10_8_p(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_log10][sv_cs][frp_p];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_pow_8_p(vcs8_t x, vcs8_t y)
{
  float _Complex (*fptr)(float _Complex, float _Complex);
  fptr = (float _Complex(*)(float _Complex, float _Complex))MTH_DISPATCH_TBL[func_pow][sv_cs][frp_p];
  return __ZGVzN8vv__mth_i_vc4vc4( x, y, fptr);
}

vcs8_t
__gc_div_8_p(vcs8_t x, vcs8_t y)
{
  float _Complex (*fptr)(float _Complex, float _Complex);
  fptr = (float _Complex(*)(float _Complex, float _Complex))MTH_DISPATCH_TBL[func_div][sv_cs][frp_p];
  return __ZGVzN8vv__mth_i_vc4vc4( x, y, fptr);
}

vcs8_t
__gc_sqrt_8_p(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_sqrt][sv_cs][frp_p];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_mod_8_p(vcs8_t x, vcs8_t y)
{
  float _Complex (*fptr)(float _Complex, float _Complex);
  fptr = (float _Complex(*)(float _Complex, float _Complex))MTH_DISPATCH_TBL[func_mod][sv_cs][frp_p];
  return __ZGVzN8vv__mth_i_vc4vc4( x, y, fptr);
}

vcs8_t
__gc_aint_8_p(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_aint][sv_cs][frp_p];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_ceil_8_p(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_ceil][sv_cs][frp_p];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_floor_8_p(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_floor][sv_cs][frp_p];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vrd8_t
__gd_acos_8_r(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_acos][sv_ds][frp_r];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_asin_8_r(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_asin][sv_ds][frp_r];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_atan_8_r(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_atan][sv_ds][frp_r];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_atan2_8_r(vrd8_t x, vrd8_t y)
{
  double (*fptr)(double, double);
  fptr = (double(*)(double, double))MTH_DISPATCH_TBL[func_atan2][sv_ds][frp_r];
  return __ZGVzN8vv__mth_i_vr8vr8( x, y, fptr);
}

vrd8_t
__gd_cos_8_r(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_cos][sv_ds][frp_r];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_sin_8_r(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_sin][sv_ds][frp_r];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_tan_8_r(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_tan][sv_ds][frp_r];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_cosh_8_r(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_cosh][sv_ds][frp_r];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_sinh_8_r(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_sinh][sv_ds][frp_r];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_tanh_8_r(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_tanh][sv_ds][frp_r];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_exp_8_r(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_exp][sv_ds][frp_r];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_log_8_r(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_log][sv_ds][frp_r];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_log10_8_r(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_log10][sv_ds][frp_r];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_pow_8_r(vrd8_t x, vrd8_t y)
{
  double (*fptr)(double, double);
  fptr = (double(*)(double, double))MTH_DISPATCH_TBL[func_pow][sv_ds][frp_r];
  return __ZGVzN8vv__mth_i_vr8vr8( x, y, fptr);
}

vrd8_t
__gd_div_8_r(vrd8_t x, vrd8_t y)
{
  double (*fptr)(double, double);
  fptr = (double(*)(double, double))MTH_DISPATCH_TBL[func_div][sv_ds][frp_r];
  return __ZGVzN8vv__mth_i_vr8vr8( x, y, fptr);
}

vrd8_t
__gd_sqrt_8_r(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_sqrt][sv_ds][frp_r];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_mod_8_r(vrd8_t x, vrd8_t y)
{
  double (*fptr)(double, double);
  fptr = (double(*)(double, double))MTH_DISPATCH_TBL[func_mod][sv_ds][frp_r];
  return __ZGVzN8vv__mth_i_vr8vr8( x, y, fptr);
}

vrd8_t
__gd_aint_8_r(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_aint][sv_ds][frp_r];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_ceil_8_r(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_ceil][sv_ds][frp_r];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrd8_t
__gd_floor_8_r(vrd8_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_floor][sv_ds][frp_r];
  return __ZGVzN8v__mth_i_vr8( x, fptr);
}

vrs16_t
__gs_acos_16_r(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_acos][sv_ss][frp_r];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_asin_16_r(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_asin][sv_ss][frp_r];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_atan_16_r(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_atan][sv_ss][frp_r];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_atan2_16_r(vrs16_t x, vrs16_t y)
{
  float (*fptr)(float, float);
  fptr = (float(*)(float, float))MTH_DISPATCH_TBL[func_atan2][sv_ss][frp_r];
  return __ZGVzN16vv__mth_i_vr4vr4( x, y, fptr);
}

vrs16_t
__gs_cos_16_r(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_cos][sv_ss][frp_r];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_sin_16_r(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_sin][sv_ss][frp_r];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_tan_16_r(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_tan][sv_ss][frp_r];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_cosh_16_r(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_cosh][sv_ss][frp_r];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_sinh_16_r(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_sinh][sv_ss][frp_r];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_tanh_16_r(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_tanh][sv_ss][frp_r];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_exp_16_r(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_exp][sv_ss][frp_r];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_log_16_r(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_log][sv_ss][frp_r];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_log10_16_r(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_log10][sv_ss][frp_r];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_pow_16_r(vrs16_t x, vrs16_t y)
{
  float (*fptr)(float, float);
  fptr = (float(*)(float, float))MTH_DISPATCH_TBL[func_pow][sv_ss][frp_r];
  return __ZGVzN16vv__mth_i_vr4vr4( x, y, fptr);
}

vrs16_t
__gs_div_16_r(vrs16_t x, vrs16_t y)
{
  float (*fptr)(float, float);
  fptr = (float(*)(float, float))MTH_DISPATCH_TBL[func_div][sv_ss][frp_r];
  return __ZGVzN16vv__mth_i_vr4vr4( x, y, fptr);
}

vrs16_t
__gs_sqrt_16_r(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_sqrt][sv_ss][frp_r];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_mod_16_r(vrs16_t x, vrs16_t y)
{
  float (*fptr)(float, float);
  fptr = (float(*)(float, float))MTH_DISPATCH_TBL[func_mod][sv_ss][frp_r];
  return __ZGVzN16vv__mth_i_vr4vr4( x, y, fptr);
}

vrs16_t
__gs_aint_16_r(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_aint][sv_ss][frp_r];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_ceil_16_r(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_ceil][sv_ss][frp_r];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vrs16_t
__gs_floor_16_r(vrs16_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_floor][sv_ss][frp_r];
  return __ZGVzN16v__mth_i_vr4( x, fptr);
}

vcd4_t
__gz_acos_4_r(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_acos][sv_zs][frp_r];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_asin_4_r(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_asin][sv_zs][frp_r];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_atan_4_r(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_atan][sv_zs][frp_r];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_atan2_4_r(vcd4_t x, vcd4_t y)
{
  double _Complex (*fptr)(double _Complex, double _Complex);
  fptr = (double _Complex(*)(double _Complex, double _Complex))MTH_DISPATCH_TBL[func_atan2][sv_zs][frp_r];
  return __ZGVzN4vv__mth_i_vc8vc8( x, y, fptr);
}

vcd4_t
__gz_cos_4_r(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_cos][sv_zs][frp_r];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_sin_4_r(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_sin][sv_zs][frp_r];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_tan_4_r(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_tan][sv_zs][frp_r];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_cosh_4_r(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_cosh][sv_zs][frp_r];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_sinh_4_r(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_sinh][sv_zs][frp_r];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_tanh_4_r(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_tanh][sv_zs][frp_r];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_exp_4_r(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_exp][sv_zs][frp_r];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_log_4_r(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_log][sv_zs][frp_r];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_log10_4_r(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_log10][sv_zs][frp_r];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_pow_4_r(vcd4_t x, vcd4_t y)
{
  double _Complex (*fptr)(double _Complex, double _Complex);
  fptr = (double _Complex(*)(double _Complex, double _Complex))MTH_DISPATCH_TBL[func_pow][sv_zs][frp_r];
  return __ZGVzN4vv__mth_i_vc8vc8( x, y, fptr);
}

vcd4_t
__gz_div_4_r(vcd4_t x, vcd4_t y)
{
  double _Complex (*fptr)(double _Complex, double _Complex);
  fptr = (double _Complex(*)(double _Complex, double _Complex))MTH_DISPATCH_TBL[func_div][sv_zs][frp_r];
  return __ZGVzN4vv__mth_i_vc8vc8( x, y, fptr);
}

vcd4_t
__gz_sqrt_4_r(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_sqrt][sv_zs][frp_r];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_mod_4_r(vcd4_t x, vcd4_t y)
{
  double _Complex (*fptr)(double _Complex, double _Complex);
  fptr = (double _Complex(*)(double _Complex, double _Complex))MTH_DISPATCH_TBL[func_mod][sv_zs][frp_r];
  return __ZGVzN4vv__mth_i_vc8vc8( x, y, fptr);
}

vcd4_t
__gz_aint_4_r(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_aint][sv_zs][frp_r];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_ceil_4_r(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_ceil][sv_zs][frp_r];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcd4_t
__gz_floor_4_r(vcd4_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_floor][sv_zs][frp_r];
  return __ZGVzN4v__mth_i_vc8( x, fptr);
}

vcs8_t
__gc_acos_8_r(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_acos][sv_cs][frp_r];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_asin_8_r(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_asin][sv_cs][frp_r];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_atan_8_r(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_atan][sv_cs][frp_r];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_atan2_8_r(vcs8_t x, vcs8_t y)
{
  float _Complex (*fptr)(float _Complex, float _Complex);
  fptr = (float _Complex(*)(float _Complex, float _Complex))MTH_DISPATCH_TBL[func_atan2][sv_cs][frp_r];
  return __ZGVzN8vv__mth_i_vc4vc4( x, y, fptr);
}

vcs8_t
__gc_cos_8_r(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_cos][sv_cs][frp_r];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_sin_8_r(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_sin][sv_cs][frp_r];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_tan_8_r(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_tan][sv_cs][frp_r];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_cosh_8_r(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_cosh][sv_cs][frp_r];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_sinh_8_r(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_sinh][sv_cs][frp_r];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_tanh_8_r(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_tanh][sv_cs][frp_r];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_exp_8_r(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_exp][sv_cs][frp_r];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_log_8_r(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_log][sv_cs][frp_r];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_log10_8_r(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_log10][sv_cs][frp_r];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_pow_8_r(vcs8_t x, vcs8_t y)
{
  float _Complex (*fptr)(float _Complex, float _Complex);
  fptr = (float _Complex(*)(float _Complex, float _Complex))MTH_DISPATCH_TBL[func_pow][sv_cs][frp_r];
  return __ZGVzN8vv__mth_i_vc4vc4( x, y, fptr);
}

vcs8_t
__gc_div_8_r(vcs8_t x, vcs8_t y)
{
  float _Complex (*fptr)(float _Complex, float _Complex);
  fptr = (float _Complex(*)(float _Complex, float _Complex))MTH_DISPATCH_TBL[func_div][sv_cs][frp_r];
  return __ZGVzN8vv__mth_i_vc4vc4( x, y, fptr);
}

vcs8_t
__gc_sqrt_8_r(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_sqrt][sv_cs][frp_r];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_mod_8_r(vcs8_t x, vcs8_t y)
{
  float _Complex (*fptr)(float _Complex, float _Complex);
  fptr = (float _Complex(*)(float _Complex, float _Complex))MTH_DISPATCH_TBL[func_mod][sv_cs][frp_r];
  return __ZGVzN8vv__mth_i_vc4vc4( x, y, fptr);
}

vcs8_t
__gc_aint_8_r(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_aint][sv_cs][frp_r];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_ceil_8_r(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_ceil][sv_cs][frp_r];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vcs8_t
__gc_floor_8_r(vcs8_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_floor][sv_cs][frp_r];
  return __ZGVzN8v__mth_i_vc4( x, fptr);
}

vrd8_t
__gd_powi1_8_f(vrd8_t x, int32_t iy)
{
  double (*fptr)(double, int32_t);
  fptr = (double(*)(double, int32_t))MTH_DISPATCH_TBL[func_powi1][sv_ds][frp_f];
  return __ZGVzN8v__mth_i_vr8si4(x, iy, fptr);
}

vrd8_t
__gd_powi_8_f(vrd8_t x, vis8_t iy)
{
  double (*fptr)(double, int32_t);
  fptr = (double(*)(double, int32_t))MTH_DISPATCH_TBL[func_powi][sv_ds][frp_f];
  return __ZGVzN8vv__mth_i_vr8vi4(x, iy, fptr);
}

vrd8_t
__gd_powk1_8_f(vrd8_t x, long long iy)
{
  double (*fptr)(double, long long);
  fptr = (double(*)(double, long long))MTH_DISPATCH_TBL[func_powk1][sv_ds][frp_f];
  return __ZGVzN8v__mth_i_vr8si8(x, iy, fptr);
}

vrd8_t
__gd_powk_8_f(vrd8_t x, vid8_t iy)
{
  double (*fptr)(double, long long);
  fptr = (double(*)(double, long long))MTH_DISPATCH_TBL[func_powk][sv_ds][frp_f];
  return __ZGVzN8vv__mth_i_vr8vi8(x, iy, fptr);
}

vrs16_t
__gs_powi1_16_f(vrs16_t x, int32_t iy)
{
  float (*fptr)(float, int32_t);
  fptr = (float(*)(float, int32_t))MTH_DISPATCH_TBL[func_powi1][sv_ss][frp_f];
  return __ZGVzN16v__mth_i_vr4si4(x, iy, fptr);
}

vrs16_t
__gs_powi_16_f(vrs16_t x, vis16_t iy)
{
  float (*fptr)(float, int32_t);
  fptr = (float(*)(float, int32_t))MTH_DISPATCH_TBL[func_powi][sv_ss][frp_f];
  return __ZGVzN16vv__mth_i_vr4vi4(x, iy, fptr);
}

vrs16_t
__gs_powk1_16_f(vrs16_t x, long long iy)
{
  float (*fptr)(float, long long);
  fptr = (float(*)(float, long long))MTH_DISPATCH_TBL[func_powk1][sv_ss][frp_f];
  return __ZGVzN16v__mth_i_vr4si8(x, iy, fptr);
}

vrs16_t
__gs_powk_16_f(vrs16_t x, vid8_t iyu, vid8_t iyl)
{
  float (*fptr)(float, long long);
  fptr = (float(*)(float, long long))MTH_DISPATCH_TBL[func_powk][sv_ss][frp_f];
  return __ZGVzN16vv__mth_i_vr4vi8(x, iyu, iyl, fptr);
}

vrd8_t
__gd_powi1_8_p(vrd8_t x, int32_t iy)
{
  double (*fptr)(double, int32_t);
  fptr = (double(*)(double, int32_t))MTH_DISPATCH_TBL[func_powi1][sv_ds][frp_p];
  return __ZGVzN8v__mth_i_vr8si4(x, iy, fptr);
}

vrd8_t
__gd_powi_8_p(vrd8_t x, vis8_t iy)
{
  double (*fptr)(double, int32_t);
  fptr = (double(*)(double, int32_t))MTH_DISPATCH_TBL[func_powi][sv_ds][frp_p];
  return __ZGVzN8vv__mth_i_vr8vi4(x, iy, fptr);
}

vrd8_t
__gd_powk1_8_p(vrd8_t x, long long iy)
{
  double (*fptr)(double, long long);
  fptr = (double(*)(double, long long))MTH_DISPATCH_TBL[func_powk1][sv_ds][frp_p];
  return __ZGVzN8v__mth_i_vr8si8(x, iy, fptr);
}

vrd8_t
__gd_powk_8_p(vrd8_t x, vid8_t iy)
{
  double (*fptr)(double, long long);
  fptr = (double(*)(double, long long))MTH_DISPATCH_TBL[func_powk][sv_ds][frp_p];
  return __ZGVzN8vv__mth_i_vr8vi8(x, iy, fptr);
}

vrs16_t
__gs_powi1_16_p(vrs16_t x, int32_t iy)
{
  float (*fptr)(float, int32_t);
  fptr = (float(*)(float, int32_t))MTH_DISPATCH_TBL[func_powi1][sv_ss][frp_p];
  return __ZGVzN16v__mth_i_vr4si4(x, iy, fptr);
}

vrs16_t
__gs_powi_16_p(vrs16_t x, vis16_t iy)
{
  float (*fptr)(float, int32_t);
  fptr = (float(*)(float, int32_t))MTH_DISPATCH_TBL[func_powi][sv_ss][frp_p];
  return __ZGVzN16vv__mth_i_vr4vi4(x, iy, fptr);
}

vrs16_t
__gs_powk1_16_p(vrs16_t x, long long iy)
{
  float (*fptr)(float, long long);
  fptr = (float(*)(float, long long))MTH_DISPATCH_TBL[func_powk1][sv_ss][frp_p];
  return __ZGVzN16v__mth_i_vr4si8(x, iy, fptr);
}

vrs16_t
__gs_powk_16_p(vrs16_t x, vid8_t iyu, vid8_t iyl)
{
  float (*fptr)(float, long long);
  fptr = (float(*)(float, long long))MTH_DISPATCH_TBL[func_powk][sv_ss][frp_p];
  return __ZGVzN16vv__mth_i_vr4vi8(x, iyu, iyl, fptr);
}

vrd8_t
__gd_powi1_8_r(vrd8_t x, int32_t iy)
{
  double (*fptr)(double, int32_t);
  fptr = (double(*)(double, int32_t))MTH_DISPATCH_TBL[func_powi1][sv_ds][frp_r];
  return __ZGVzN8v__mth_i_vr8si4(x, iy, fptr);
}

vrd8_t
__gd_powi_8_r(vrd8_t x, vis8_t iy)
{
  double (*fptr)(double, int32_t);
  fptr = (double(*)(double, int32_t))MTH_DISPATCH_TBL[func_powi][sv_ds][frp_r];
  return __ZGVzN8vv__mth_i_vr8vi4(x, iy, fptr);
}

vrd8_t
__gd_powk1_8_r(vrd8_t x, long long iy)
{
  double (*fptr)(double, long long);
  fptr = (double(*)(double, long long))MTH_DISPATCH_TBL[func_powk1][sv_ds][frp_r];
  return __ZGVzN8v__mth_i_vr8si8(x, iy, fptr);
}

vrd8_t
__gd_powk_8_r(vrd8_t x, vid8_t iy)
{
  double (*fptr)(double, long long);
  fptr = (double(*)(double, long long))MTH_DISPATCH_TBL[func_powk][sv_ds][frp_r];
  return __ZGVzN8vv__mth_i_vr8vi8(x, iy, fptr);
}

vrs16_t
__gs_powi1_16_r(vrs16_t x, int32_t iy)
{
  float (*fptr)(float, int32_t);
  fptr = (float(*)(float, int32_t))MTH_DISPATCH_TBL[func_powi1][sv_ss][frp_r];
  return __ZGVzN16v__mth_i_vr4si4(x, iy, fptr);
}

vrs16_t
__gs_powi_16_r(vrs16_t x, vis16_t iy)
{
  float (*fptr)(float, int32_t);
  fptr = (float(*)(float, int32_t))MTH_DISPATCH_TBL[func_powi][sv_ss][frp_r];
  return __ZGVzN16vv__mth_i_vr4vi4(x, iy, fptr);
}

vrs16_t
__gs_powk1_16_r(vrs16_t x, long long iy)
{
  float (*fptr)(float, long long);
  fptr = (float(*)(float, long long))MTH_DISPATCH_TBL[func_powk1][sv_ss][frp_r];
  return __ZGVzN16v__mth_i_vr4si8(x, iy, fptr);
}

vrs16_t
__gs_powk_16_r(vrs16_t x, vid8_t iyu, vid8_t iyl)
{
  float (*fptr)(float, long long);
  fptr = (float(*)(float, long long))MTH_DISPATCH_TBL[func_powk][sv_ss][frp_r];
  return __ZGVzN16vv__mth_i_vr4vi8(x, iyu, iyl, fptr);
}
