/*
 *     Copyright (c) 2018-2019, NVIDIA CORPORATION.  All rights reserved.
 *
 * NVIDIA CORPORATION and its licensors retain all intellectual property
 * and proprietary rights in and to this software, related documentation
 * and any modifications thereto.  Any use, reproduction, disclosure or
 * distribution of this software and related documentation without an express
 * license agreement from NVIDIA CORPORATION is strictly prohibited.
 *
 */


/*
 *
 * WARNING - this file is automatically generated. DO NOT EDIT.
 *
 */

#include "mth_intrinsics.h"
#include "mth_tbldefs.h"
#include <complex.h>



vrd4_t
__gd_acos_4_f(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_acos][sv_ds][frp_f];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_asin_4_f(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_asin][sv_ds][frp_f];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_atan_4_f(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_atan][sv_ds][frp_f];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_atan2_4_f(vrd4_t x, vrd4_t y)
{
  double (*fptr)(double, double);
  fptr = (double(*)(double, double))MTH_DISPATCH_TBL[func_atan2][sv_ds][frp_f];
  return __ZGVyN4vv__mth_i_vr8vr8( x, y, fptr);
}

vrd4_t
__gd_cos_4_f(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_cos][sv_ds][frp_f];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_sin_4_f(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_sin][sv_ds][frp_f];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_tan_4_f(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_tan][sv_ds][frp_f];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_cosh_4_f(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_cosh][sv_ds][frp_f];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_sinh_4_f(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_sinh][sv_ds][frp_f];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_tanh_4_f(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_tanh][sv_ds][frp_f];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_exp_4_f(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_exp][sv_ds][frp_f];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_log_4_f(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_log][sv_ds][frp_f];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_log10_4_f(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_log10][sv_ds][frp_f];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_pow_4_f(vrd4_t x, vrd4_t y)
{
  double (*fptr)(double, double);
  fptr = (double(*)(double, double))MTH_DISPATCH_TBL[func_pow][sv_ds][frp_f];
  return __ZGVyN4vv__mth_i_vr8vr8( x, y, fptr);
}

vrd4_t
__gd_div_4_f(vrd4_t x, vrd4_t y)
{
  double (*fptr)(double, double);
  fptr = (double(*)(double, double))MTH_DISPATCH_TBL[func_div][sv_ds][frp_f];
  return __ZGVyN4vv__mth_i_vr8vr8( x, y, fptr);
}

vrd4_t
__gd_sqrt_4_f(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_sqrt][sv_ds][frp_f];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_mod_4_f(vrd4_t x, vrd4_t y)
{
  double (*fptr)(double, double);
  fptr = (double(*)(double, double))MTH_DISPATCH_TBL[func_mod][sv_ds][frp_f];
  return __ZGVyN4vv__mth_i_vr8vr8( x, y, fptr);
}

vrd4_t
__gd_aint_4_f(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_aint][sv_ds][frp_f];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_ceil_4_f(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_ceil][sv_ds][frp_f];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_floor_4_f(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_floor][sv_ds][frp_f];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrs8_t
__gs_acos_8_f(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_acos][sv_ss][frp_f];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_asin_8_f(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_asin][sv_ss][frp_f];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_atan_8_f(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_atan][sv_ss][frp_f];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_atan2_8_f(vrs8_t x, vrs8_t y)
{
  float (*fptr)(float, float);
  fptr = (float(*)(float, float))MTH_DISPATCH_TBL[func_atan2][sv_ss][frp_f];
  return __ZGVyN8vv__mth_i_vr4vr4( x, y, fptr);
}

vrs8_t
__gs_cos_8_f(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_cos][sv_ss][frp_f];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_sin_8_f(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_sin][sv_ss][frp_f];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_tan_8_f(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_tan][sv_ss][frp_f];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_cosh_8_f(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_cosh][sv_ss][frp_f];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_sinh_8_f(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_sinh][sv_ss][frp_f];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_tanh_8_f(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_tanh][sv_ss][frp_f];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_exp_8_f(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_exp][sv_ss][frp_f];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_log_8_f(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_log][sv_ss][frp_f];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_log10_8_f(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_log10][sv_ss][frp_f];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_pow_8_f(vrs8_t x, vrs8_t y)
{
  float (*fptr)(float, float);
  fptr = (float(*)(float, float))MTH_DISPATCH_TBL[func_pow][sv_ss][frp_f];
  return __ZGVyN8vv__mth_i_vr4vr4( x, y, fptr);
}

vrs8_t
__gs_div_8_f(vrs8_t x, vrs8_t y)
{
  float (*fptr)(float, float);
  fptr = (float(*)(float, float))MTH_DISPATCH_TBL[func_div][sv_ss][frp_f];
  return __ZGVyN8vv__mth_i_vr4vr4( x, y, fptr);
}

vrs8_t
__gs_sqrt_8_f(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_sqrt][sv_ss][frp_f];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_mod_8_f(vrs8_t x, vrs8_t y)
{
  float (*fptr)(float, float);
  fptr = (float(*)(float, float))MTH_DISPATCH_TBL[func_mod][sv_ss][frp_f];
  return __ZGVyN8vv__mth_i_vr4vr4( x, y, fptr);
}

vrs8_t
__gs_aint_8_f(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_aint][sv_ss][frp_f];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_ceil_8_f(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_ceil][sv_ss][frp_f];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_floor_8_f(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_floor][sv_ss][frp_f];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vcd2_t
__gz_acos_2_f(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_acos][sv_zs][frp_f];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_asin_2_f(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_asin][sv_zs][frp_f];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_atan_2_f(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_atan][sv_zs][frp_f];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_atan2_2_f(vcd2_t x, vcd2_t y)
{
  double _Complex (*fptr)(double _Complex, double _Complex);
  fptr = (double _Complex(*)(double _Complex, double _Complex))MTH_DISPATCH_TBL[func_atan2][sv_zs][frp_f];
  return __ZGVyN2vv__mth_i_vc8vc8( x, y, fptr);
}

vcd2_t
__gz_cos_2_f(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_cos][sv_zs][frp_f];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_sin_2_f(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_sin][sv_zs][frp_f];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_tan_2_f(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_tan][sv_zs][frp_f];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_cosh_2_f(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_cosh][sv_zs][frp_f];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_sinh_2_f(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_sinh][sv_zs][frp_f];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_tanh_2_f(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_tanh][sv_zs][frp_f];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_exp_2_f(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_exp][sv_zs][frp_f];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_log_2_f(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_log][sv_zs][frp_f];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_log10_2_f(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_log10][sv_zs][frp_f];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_pow_2_f(vcd2_t x, vcd2_t y)
{
  double _Complex (*fptr)(double _Complex, double _Complex);
  fptr = (double _Complex(*)(double _Complex, double _Complex))MTH_DISPATCH_TBL[func_pow][sv_zs][frp_f];
  return __ZGVyN2vv__mth_i_vc8vc8( x, y, fptr);
}

vcd2_t
__gz_div_2_f(vcd2_t x, vcd2_t y)
{
  double _Complex (*fptr)(double _Complex, double _Complex);
  fptr = (double _Complex(*)(double _Complex, double _Complex))MTH_DISPATCH_TBL[func_div][sv_zs][frp_f];
  return __ZGVyN2vv__mth_i_vc8vc8( x, y, fptr);
}

vcd2_t
__gz_sqrt_2_f(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_sqrt][sv_zs][frp_f];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_mod_2_f(vcd2_t x, vcd2_t y)
{
  double _Complex (*fptr)(double _Complex, double _Complex);
  fptr = (double _Complex(*)(double _Complex, double _Complex))MTH_DISPATCH_TBL[func_mod][sv_zs][frp_f];
  return __ZGVyN2vv__mth_i_vc8vc8( x, y, fptr);
}

vcd2_t
__gz_aint_2_f(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_aint][sv_zs][frp_f];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_ceil_2_f(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_ceil][sv_zs][frp_f];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_floor_2_f(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_floor][sv_zs][frp_f];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcs4_t
__gc_acos_4_f(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_acos][sv_cs][frp_f];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_asin_4_f(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_asin][sv_cs][frp_f];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_atan_4_f(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_atan][sv_cs][frp_f];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_atan2_4_f(vcs4_t x, vcs4_t y)
{
  float _Complex (*fptr)(float _Complex, float _Complex);
  fptr = (float _Complex(*)(float _Complex, float _Complex))MTH_DISPATCH_TBL[func_atan2][sv_cs][frp_f];
  return __ZGVyN4vv__mth_i_vc4vc4( x, y, fptr);
}

vcs4_t
__gc_cos_4_f(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_cos][sv_cs][frp_f];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_sin_4_f(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_sin][sv_cs][frp_f];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_tan_4_f(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_tan][sv_cs][frp_f];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_cosh_4_f(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_cosh][sv_cs][frp_f];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_sinh_4_f(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_sinh][sv_cs][frp_f];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_tanh_4_f(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_tanh][sv_cs][frp_f];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_exp_4_f(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_exp][sv_cs][frp_f];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_log_4_f(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_log][sv_cs][frp_f];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_log10_4_f(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_log10][sv_cs][frp_f];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_pow_4_f(vcs4_t x, vcs4_t y)
{
  float _Complex (*fptr)(float _Complex, float _Complex);
  fptr = (float _Complex(*)(float _Complex, float _Complex))MTH_DISPATCH_TBL[func_pow][sv_cs][frp_f];
  return __ZGVyN4vv__mth_i_vc4vc4( x, y, fptr);
}

vcs4_t
__gc_div_4_f(vcs4_t x, vcs4_t y)
{
  float _Complex (*fptr)(float _Complex, float _Complex);
  fptr = (float _Complex(*)(float _Complex, float _Complex))MTH_DISPATCH_TBL[func_div][sv_cs][frp_f];
  return __ZGVyN4vv__mth_i_vc4vc4( x, y, fptr);
}

vcs4_t
__gc_sqrt_4_f(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_sqrt][sv_cs][frp_f];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_mod_4_f(vcs4_t x, vcs4_t y)
{
  float _Complex (*fptr)(float _Complex, float _Complex);
  fptr = (float _Complex(*)(float _Complex, float _Complex))MTH_DISPATCH_TBL[func_mod][sv_cs][frp_f];
  return __ZGVyN4vv__mth_i_vc4vc4( x, y, fptr);
}

vcs4_t
__gc_aint_4_f(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_aint][sv_cs][frp_f];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_ceil_4_f(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_ceil][sv_cs][frp_f];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_floor_4_f(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_floor][sv_cs][frp_f];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vrd4_t
__gd_acos_4_p(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_acos][sv_ds][frp_p];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_asin_4_p(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_asin][sv_ds][frp_p];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_atan_4_p(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_atan][sv_ds][frp_p];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_atan2_4_p(vrd4_t x, vrd4_t y)
{
  double (*fptr)(double, double);
  fptr = (double(*)(double, double))MTH_DISPATCH_TBL[func_atan2][sv_ds][frp_p];
  return __ZGVyN4vv__mth_i_vr8vr8( x, y, fptr);
}

vrd4_t
__gd_cos_4_p(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_cos][sv_ds][frp_p];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_sin_4_p(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_sin][sv_ds][frp_p];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_tan_4_p(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_tan][sv_ds][frp_p];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_cosh_4_p(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_cosh][sv_ds][frp_p];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_sinh_4_p(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_sinh][sv_ds][frp_p];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_tanh_4_p(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_tanh][sv_ds][frp_p];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_exp_4_p(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_exp][sv_ds][frp_p];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_log_4_p(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_log][sv_ds][frp_p];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_log10_4_p(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_log10][sv_ds][frp_p];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_pow_4_p(vrd4_t x, vrd4_t y)
{
  double (*fptr)(double, double);
  fptr = (double(*)(double, double))MTH_DISPATCH_TBL[func_pow][sv_ds][frp_p];
  return __ZGVyN4vv__mth_i_vr8vr8( x, y, fptr);
}

vrd4_t
__gd_div_4_p(vrd4_t x, vrd4_t y)
{
  double (*fptr)(double, double);
  fptr = (double(*)(double, double))MTH_DISPATCH_TBL[func_div][sv_ds][frp_p];
  return __ZGVyN4vv__mth_i_vr8vr8( x, y, fptr);
}

vrd4_t
__gd_sqrt_4_p(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_sqrt][sv_ds][frp_p];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_mod_4_p(vrd4_t x, vrd4_t y)
{
  double (*fptr)(double, double);
  fptr = (double(*)(double, double))MTH_DISPATCH_TBL[func_mod][sv_ds][frp_p];
  return __ZGVyN4vv__mth_i_vr8vr8( x, y, fptr);
}

vrd4_t
__gd_aint_4_p(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_aint][sv_ds][frp_p];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_ceil_4_p(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_ceil][sv_ds][frp_p];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_floor_4_p(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_floor][sv_ds][frp_p];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrs8_t
__gs_acos_8_p(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_acos][sv_ss][frp_p];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_asin_8_p(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_asin][sv_ss][frp_p];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_atan_8_p(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_atan][sv_ss][frp_p];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_atan2_8_p(vrs8_t x, vrs8_t y)
{
  float (*fptr)(float, float);
  fptr = (float(*)(float, float))MTH_DISPATCH_TBL[func_atan2][sv_ss][frp_p];
  return __ZGVyN8vv__mth_i_vr4vr4( x, y, fptr);
}

vrs8_t
__gs_cos_8_p(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_cos][sv_ss][frp_p];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_sin_8_p(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_sin][sv_ss][frp_p];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_tan_8_p(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_tan][sv_ss][frp_p];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_cosh_8_p(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_cosh][sv_ss][frp_p];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_sinh_8_p(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_sinh][sv_ss][frp_p];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_tanh_8_p(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_tanh][sv_ss][frp_p];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_exp_8_p(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_exp][sv_ss][frp_p];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_log_8_p(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_log][sv_ss][frp_p];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_log10_8_p(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_log10][sv_ss][frp_p];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_pow_8_p(vrs8_t x, vrs8_t y)
{
  float (*fptr)(float, float);
  fptr = (float(*)(float, float))MTH_DISPATCH_TBL[func_pow][sv_ss][frp_p];
  return __ZGVyN8vv__mth_i_vr4vr4( x, y, fptr);
}

vrs8_t
__gs_div_8_p(vrs8_t x, vrs8_t y)
{
  float (*fptr)(float, float);
  fptr = (float(*)(float, float))MTH_DISPATCH_TBL[func_div][sv_ss][frp_p];
  return __ZGVyN8vv__mth_i_vr4vr4( x, y, fptr);
}

vrs8_t
__gs_sqrt_8_p(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_sqrt][sv_ss][frp_p];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_mod_8_p(vrs8_t x, vrs8_t y)
{
  float (*fptr)(float, float);
  fptr = (float(*)(float, float))MTH_DISPATCH_TBL[func_mod][sv_ss][frp_p];
  return __ZGVyN8vv__mth_i_vr4vr4( x, y, fptr);
}

vrs8_t
__gs_aint_8_p(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_aint][sv_ss][frp_p];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_ceil_8_p(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_ceil][sv_ss][frp_p];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_floor_8_p(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_floor][sv_ss][frp_p];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vcd2_t
__gz_acos_2_p(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_acos][sv_zs][frp_p];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_asin_2_p(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_asin][sv_zs][frp_p];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_atan_2_p(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_atan][sv_zs][frp_p];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_atan2_2_p(vcd2_t x, vcd2_t y)
{
  double _Complex (*fptr)(double _Complex, double _Complex);
  fptr = (double _Complex(*)(double _Complex, double _Complex))MTH_DISPATCH_TBL[func_atan2][sv_zs][frp_p];
  return __ZGVyN2vv__mth_i_vc8vc8( x, y, fptr);
}

vcd2_t
__gz_cos_2_p(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_cos][sv_zs][frp_p];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_sin_2_p(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_sin][sv_zs][frp_p];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_tan_2_p(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_tan][sv_zs][frp_p];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_cosh_2_p(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_cosh][sv_zs][frp_p];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_sinh_2_p(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_sinh][sv_zs][frp_p];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_tanh_2_p(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_tanh][sv_zs][frp_p];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_exp_2_p(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_exp][sv_zs][frp_p];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_log_2_p(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_log][sv_zs][frp_p];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_log10_2_p(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_log10][sv_zs][frp_p];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_pow_2_p(vcd2_t x, vcd2_t y)
{
  double _Complex (*fptr)(double _Complex, double _Complex);
  fptr = (double _Complex(*)(double _Complex, double _Complex))MTH_DISPATCH_TBL[func_pow][sv_zs][frp_p];
  return __ZGVyN2vv__mth_i_vc8vc8( x, y, fptr);
}

vcd2_t
__gz_div_2_p(vcd2_t x, vcd2_t y)
{
  double _Complex (*fptr)(double _Complex, double _Complex);
  fptr = (double _Complex(*)(double _Complex, double _Complex))MTH_DISPATCH_TBL[func_div][sv_zs][frp_p];
  return __ZGVyN2vv__mth_i_vc8vc8( x, y, fptr);
}

vcd2_t
__gz_sqrt_2_p(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_sqrt][sv_zs][frp_p];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_mod_2_p(vcd2_t x, vcd2_t y)
{
  double _Complex (*fptr)(double _Complex, double _Complex);
  fptr = (double _Complex(*)(double _Complex, double _Complex))MTH_DISPATCH_TBL[func_mod][sv_zs][frp_p];
  return __ZGVyN2vv__mth_i_vc8vc8( x, y, fptr);
}

vcd2_t
__gz_aint_2_p(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_aint][sv_zs][frp_p];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_ceil_2_p(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_ceil][sv_zs][frp_p];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_floor_2_p(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_floor][sv_zs][frp_p];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcs4_t
__gc_acos_4_p(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_acos][sv_cs][frp_p];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_asin_4_p(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_asin][sv_cs][frp_p];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_atan_4_p(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_atan][sv_cs][frp_p];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_atan2_4_p(vcs4_t x, vcs4_t y)
{
  float _Complex (*fptr)(float _Complex, float _Complex);
  fptr = (float _Complex(*)(float _Complex, float _Complex))MTH_DISPATCH_TBL[func_atan2][sv_cs][frp_p];
  return __ZGVyN4vv__mth_i_vc4vc4( x, y, fptr);
}

vcs4_t
__gc_cos_4_p(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_cos][sv_cs][frp_p];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_sin_4_p(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_sin][sv_cs][frp_p];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_tan_4_p(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_tan][sv_cs][frp_p];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_cosh_4_p(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_cosh][sv_cs][frp_p];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_sinh_4_p(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_sinh][sv_cs][frp_p];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_tanh_4_p(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_tanh][sv_cs][frp_p];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_exp_4_p(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_exp][sv_cs][frp_p];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_log_4_p(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_log][sv_cs][frp_p];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_log10_4_p(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_log10][sv_cs][frp_p];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_pow_4_p(vcs4_t x, vcs4_t y)
{
  float _Complex (*fptr)(float _Complex, float _Complex);
  fptr = (float _Complex(*)(float _Complex, float _Complex))MTH_DISPATCH_TBL[func_pow][sv_cs][frp_p];
  return __ZGVyN4vv__mth_i_vc4vc4( x, y, fptr);
}

vcs4_t
__gc_div_4_p(vcs4_t x, vcs4_t y)
{
  float _Complex (*fptr)(float _Complex, float _Complex);
  fptr = (float _Complex(*)(float _Complex, float _Complex))MTH_DISPATCH_TBL[func_div][sv_cs][frp_p];
  return __ZGVyN4vv__mth_i_vc4vc4( x, y, fptr);
}

vcs4_t
__gc_sqrt_4_p(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_sqrt][sv_cs][frp_p];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_mod_4_p(vcs4_t x, vcs4_t y)
{
  float _Complex (*fptr)(float _Complex, float _Complex);
  fptr = (float _Complex(*)(float _Complex, float _Complex))MTH_DISPATCH_TBL[func_mod][sv_cs][frp_p];
  return __ZGVyN4vv__mth_i_vc4vc4( x, y, fptr);
}

vcs4_t
__gc_aint_4_p(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_aint][sv_cs][frp_p];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_ceil_4_p(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_ceil][sv_cs][frp_p];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_floor_4_p(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_floor][sv_cs][frp_p];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vrd4_t
__gd_acos_4_r(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_acos][sv_ds][frp_r];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_asin_4_r(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_asin][sv_ds][frp_r];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_atan_4_r(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_atan][sv_ds][frp_r];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_atan2_4_r(vrd4_t x, vrd4_t y)
{
  double (*fptr)(double, double);
  fptr = (double(*)(double, double))MTH_DISPATCH_TBL[func_atan2][sv_ds][frp_r];
  return __ZGVyN4vv__mth_i_vr8vr8( x, y, fptr);
}

vrd4_t
__gd_cos_4_r(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_cos][sv_ds][frp_r];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_sin_4_r(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_sin][sv_ds][frp_r];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_tan_4_r(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_tan][sv_ds][frp_r];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_cosh_4_r(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_cosh][sv_ds][frp_r];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_sinh_4_r(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_sinh][sv_ds][frp_r];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_tanh_4_r(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_tanh][sv_ds][frp_r];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_exp_4_r(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_exp][sv_ds][frp_r];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_log_4_r(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_log][sv_ds][frp_r];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_log10_4_r(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_log10][sv_ds][frp_r];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_pow_4_r(vrd4_t x, vrd4_t y)
{
  double (*fptr)(double, double);
  fptr = (double(*)(double, double))MTH_DISPATCH_TBL[func_pow][sv_ds][frp_r];
  return __ZGVyN4vv__mth_i_vr8vr8( x, y, fptr);
}

vrd4_t
__gd_div_4_r(vrd4_t x, vrd4_t y)
{
  double (*fptr)(double, double);
  fptr = (double(*)(double, double))MTH_DISPATCH_TBL[func_div][sv_ds][frp_r];
  return __ZGVyN4vv__mth_i_vr8vr8( x, y, fptr);
}

vrd4_t
__gd_sqrt_4_r(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_sqrt][sv_ds][frp_r];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_mod_4_r(vrd4_t x, vrd4_t y)
{
  double (*fptr)(double, double);
  fptr = (double(*)(double, double))MTH_DISPATCH_TBL[func_mod][sv_ds][frp_r];
  return __ZGVyN4vv__mth_i_vr8vr8( x, y, fptr);
}

vrd4_t
__gd_aint_4_r(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_aint][sv_ds][frp_r];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_ceil_4_r(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_ceil][sv_ds][frp_r];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrd4_t
__gd_floor_4_r(vrd4_t x)
{
  double (*fptr)(double);
  fptr = (double(*)(double))MTH_DISPATCH_TBL[func_floor][sv_ds][frp_r];
  return __ZGVyN4v__mth_i_vr8( x, fptr);
}

vrs8_t
__gs_acos_8_r(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_acos][sv_ss][frp_r];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_asin_8_r(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_asin][sv_ss][frp_r];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_atan_8_r(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_atan][sv_ss][frp_r];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_atan2_8_r(vrs8_t x, vrs8_t y)
{
  float (*fptr)(float, float);
  fptr = (float(*)(float, float))MTH_DISPATCH_TBL[func_atan2][sv_ss][frp_r];
  return __ZGVyN8vv__mth_i_vr4vr4( x, y, fptr);
}

vrs8_t
__gs_cos_8_r(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_cos][sv_ss][frp_r];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_sin_8_r(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_sin][sv_ss][frp_r];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_tan_8_r(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_tan][sv_ss][frp_r];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_cosh_8_r(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_cosh][sv_ss][frp_r];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_sinh_8_r(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_sinh][sv_ss][frp_r];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_tanh_8_r(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_tanh][sv_ss][frp_r];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_exp_8_r(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_exp][sv_ss][frp_r];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_log_8_r(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_log][sv_ss][frp_r];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_log10_8_r(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_log10][sv_ss][frp_r];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_pow_8_r(vrs8_t x, vrs8_t y)
{
  float (*fptr)(float, float);
  fptr = (float(*)(float, float))MTH_DISPATCH_TBL[func_pow][sv_ss][frp_r];
  return __ZGVyN8vv__mth_i_vr4vr4( x, y, fptr);
}

vrs8_t
__gs_div_8_r(vrs8_t x, vrs8_t y)
{
  float (*fptr)(float, float);
  fptr = (float(*)(float, float))MTH_DISPATCH_TBL[func_div][sv_ss][frp_r];
  return __ZGVyN8vv__mth_i_vr4vr4( x, y, fptr);
}

vrs8_t
__gs_sqrt_8_r(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_sqrt][sv_ss][frp_r];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_mod_8_r(vrs8_t x, vrs8_t y)
{
  float (*fptr)(float, float);
  fptr = (float(*)(float, float))MTH_DISPATCH_TBL[func_mod][sv_ss][frp_r];
  return __ZGVyN8vv__mth_i_vr4vr4( x, y, fptr);
}

vrs8_t
__gs_aint_8_r(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_aint][sv_ss][frp_r];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_ceil_8_r(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_ceil][sv_ss][frp_r];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vrs8_t
__gs_floor_8_r(vrs8_t x)
{
  float (*fptr)(float);
  fptr = (float(*)(float))MTH_DISPATCH_TBL[func_floor][sv_ss][frp_r];
  return __ZGVyN8v__mth_i_vr4( x, fptr);
}

vcd2_t
__gz_acos_2_r(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_acos][sv_zs][frp_r];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_asin_2_r(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_asin][sv_zs][frp_r];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_atan_2_r(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_atan][sv_zs][frp_r];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_atan2_2_r(vcd2_t x, vcd2_t y)
{
  double _Complex (*fptr)(double _Complex, double _Complex);
  fptr = (double _Complex(*)(double _Complex, double _Complex))MTH_DISPATCH_TBL[func_atan2][sv_zs][frp_r];
  return __ZGVyN2vv__mth_i_vc8vc8( x, y, fptr);
}

vcd2_t
__gz_cos_2_r(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_cos][sv_zs][frp_r];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_sin_2_r(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_sin][sv_zs][frp_r];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_tan_2_r(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_tan][sv_zs][frp_r];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_cosh_2_r(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_cosh][sv_zs][frp_r];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_sinh_2_r(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_sinh][sv_zs][frp_r];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_tanh_2_r(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_tanh][sv_zs][frp_r];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_exp_2_r(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_exp][sv_zs][frp_r];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_log_2_r(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_log][sv_zs][frp_r];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_log10_2_r(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_log10][sv_zs][frp_r];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_pow_2_r(vcd2_t x, vcd2_t y)
{
  double _Complex (*fptr)(double _Complex, double _Complex);
  fptr = (double _Complex(*)(double _Complex, double _Complex))MTH_DISPATCH_TBL[func_pow][sv_zs][frp_r];
  return __ZGVyN2vv__mth_i_vc8vc8( x, y, fptr);
}

vcd2_t
__gz_div_2_r(vcd2_t x, vcd2_t y)
{
  double _Complex (*fptr)(double _Complex, double _Complex);
  fptr = (double _Complex(*)(double _Complex, double _Complex))MTH_DISPATCH_TBL[func_div][sv_zs][frp_r];
  return __ZGVyN2vv__mth_i_vc8vc8( x, y, fptr);
}

vcd2_t
__gz_sqrt_2_r(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_sqrt][sv_zs][frp_r];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_mod_2_r(vcd2_t x, vcd2_t y)
{
  double _Complex (*fptr)(double _Complex, double _Complex);
  fptr = (double _Complex(*)(double _Complex, double _Complex))MTH_DISPATCH_TBL[func_mod][sv_zs][frp_r];
  return __ZGVyN2vv__mth_i_vc8vc8( x, y, fptr);
}

vcd2_t
__gz_aint_2_r(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_aint][sv_zs][frp_r];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_ceil_2_r(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_ceil][sv_zs][frp_r];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcd2_t
__gz_floor_2_r(vcd2_t x)
{
  double _Complex (*fptr)(double _Complex);
  fptr = (double _Complex(*)(double _Complex))MTH_DISPATCH_TBL[func_floor][sv_zs][frp_r];
  return __ZGVyN2v__mth_i_vc8( x, fptr);
}

vcs4_t
__gc_acos_4_r(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_acos][sv_cs][frp_r];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_asin_4_r(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_asin][sv_cs][frp_r];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_atan_4_r(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_atan][sv_cs][frp_r];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_atan2_4_r(vcs4_t x, vcs4_t y)
{
  float _Complex (*fptr)(float _Complex, float _Complex);
  fptr = (float _Complex(*)(float _Complex, float _Complex))MTH_DISPATCH_TBL[func_atan2][sv_cs][frp_r];
  return __ZGVyN4vv__mth_i_vc4vc4( x, y, fptr);
}

vcs4_t
__gc_cos_4_r(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_cos][sv_cs][frp_r];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_sin_4_r(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_sin][sv_cs][frp_r];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_tan_4_r(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_tan][sv_cs][frp_r];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_cosh_4_r(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_cosh][sv_cs][frp_r];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_sinh_4_r(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_sinh][sv_cs][frp_r];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_tanh_4_r(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_tanh][sv_cs][frp_r];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_exp_4_r(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_exp][sv_cs][frp_r];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_log_4_r(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_log][sv_cs][frp_r];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_log10_4_r(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_log10][sv_cs][frp_r];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_pow_4_r(vcs4_t x, vcs4_t y)
{
  float _Complex (*fptr)(float _Complex, float _Complex);
  fptr = (float _Complex(*)(float _Complex, float _Complex))MTH_DISPATCH_TBL[func_pow][sv_cs][frp_r];
  return __ZGVyN4vv__mth_i_vc4vc4( x, y, fptr);
}

vcs4_t
__gc_div_4_r(vcs4_t x, vcs4_t y)
{
  float _Complex (*fptr)(float _Complex, float _Complex);
  fptr = (float _Complex(*)(float _Complex, float _Complex))MTH_DISPATCH_TBL[func_div][sv_cs][frp_r];
  return __ZGVyN4vv__mth_i_vc4vc4( x, y, fptr);
}

vcs4_t
__gc_sqrt_4_r(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_sqrt][sv_cs][frp_r];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_mod_4_r(vcs4_t x, vcs4_t y)
{
  float _Complex (*fptr)(float _Complex, float _Complex);
  fptr = (float _Complex(*)(float _Complex, float _Complex))MTH_DISPATCH_TBL[func_mod][sv_cs][frp_r];
  return __ZGVyN4vv__mth_i_vc4vc4( x, y, fptr);
}

vcs4_t
__gc_aint_4_r(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_aint][sv_cs][frp_r];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_ceil_4_r(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_ceil][sv_cs][frp_r];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vcs4_t
__gc_floor_4_r(vcs4_t x)
{
  float _Complex (*fptr)(float _Complex);
  fptr = (float _Complex(*)(float _Complex))MTH_DISPATCH_TBL[func_floor][sv_cs][frp_r];
  return __ZGVyN4v__mth_i_vc4( x, fptr);
}

vrd4_t
__gd_powi1_4_f(vrd4_t x, int32_t iy)
{
  double (*fptr)(double, int32_t);
  fptr = (double(*)(double, int32_t))MTH_DISPATCH_TBL[func_powi1][sv_ds][frp_f];
  return __ZGVyN4v__mth_i_vr8si4(x, iy, fptr);
}

vrd4_t
__gd_powi_4_f(vrd4_t x, vis4_t iy)
{
  double (*fptr)(double, int32_t);
  fptr = (double(*)(double, int32_t))MTH_DISPATCH_TBL[func_powi][sv_ds][frp_f];
  return __ZGVyN4vv__mth_i_vr8vi4(x, iy, fptr);
}

vrd4_t
__gd_powk1_4_f(vrd4_t x, long long iy)
{
  double (*fptr)(double, long long);
  fptr = (double(*)(double, long long))MTH_DISPATCH_TBL[func_powk1][sv_ds][frp_f];
  return __ZGVyN4v__mth_i_vr8si8(x, iy, fptr);
}

vrd4_t
__gd_powk_4_f(vrd4_t x, vid4_t iy)
{
  double (*fptr)(double, long long);
  fptr = (double(*)(double, long long))MTH_DISPATCH_TBL[func_powk][sv_ds][frp_f];
  return __ZGVyN4vv__mth_i_vr8vi8(x, iy, fptr);
}

vrs8_t
__gs_powi1_8_f(vrs8_t x, int32_t iy)
{
  float (*fptr)(float, int32_t);
  fptr = (float(*)(float, int32_t))MTH_DISPATCH_TBL[func_powi1][sv_ss][frp_f];
  return __ZGVyN8v__mth_i_vr4si4(x, iy, fptr);
}

vrs8_t
__gs_powi_8_f(vrs8_t x, vis8_t iy)
{
  float (*fptr)(float, int32_t);
  fptr = (float(*)(float, int32_t))MTH_DISPATCH_TBL[func_powi][sv_ss][frp_f];
  return __ZGVyN8vv__mth_i_vr4vi4(x, iy, fptr);
}

vrs8_t
__gs_powk1_8_f(vrs8_t x, long long iy)
{
  float (*fptr)(float, long long);
  fptr = (float(*)(float, long long))MTH_DISPATCH_TBL[func_powk1][sv_ss][frp_f];
  return __ZGVyN8v__mth_i_vr4si8(x, iy, fptr);
}

vrs8_t
__gs_powk_8_f(vrs8_t x, vid4_t iyu, vid4_t iyl)
{
  float (*fptr)(float, long long);
  fptr = (float(*)(float, long long))MTH_DISPATCH_TBL[func_powk][sv_ss][frp_f];
  return __ZGVyN8vv__mth_i_vr4vi8(x, iyu, iyl, fptr);
}

vrd4_t
__gd_powi1_4_p(vrd4_t x, int32_t iy)
{
  double (*fptr)(double, int32_t);
  fptr = (double(*)(double, int32_t))MTH_DISPATCH_TBL[func_powi1][sv_ds][frp_p];
  return __ZGVyN4v__mth_i_vr8si4(x, iy, fptr);
}

vrd4_t
__gd_powi_4_p(vrd4_t x, vis4_t iy)
{
  double (*fptr)(double, int32_t);
  fptr = (double(*)(double, int32_t))MTH_DISPATCH_TBL[func_powi][sv_ds][frp_p];
  return __ZGVyN4vv__mth_i_vr8vi4(x, iy, fptr);
}

vrd4_t
__gd_powk1_4_p(vrd4_t x, long long iy)
{
  double (*fptr)(double, long long);
  fptr = (double(*)(double, long long))MTH_DISPATCH_TBL[func_powk1][sv_ds][frp_p];
  return __ZGVyN4v__mth_i_vr8si8(x, iy, fptr);
}

vrd4_t
__gd_powk_4_p(vrd4_t x, vid4_t iy)
{
  double (*fptr)(double, long long);
  fptr = (double(*)(double, long long))MTH_DISPATCH_TBL[func_powk][sv_ds][frp_p];
  return __ZGVyN4vv__mth_i_vr8vi8(x, iy, fptr);
}

vrs8_t
__gs_powi1_8_p(vrs8_t x, int32_t iy)
{
  float (*fptr)(float, int32_t);
  fptr = (float(*)(float, int32_t))MTH_DISPATCH_TBL[func_powi1][sv_ss][frp_p];
  return __ZGVyN8v__mth_i_vr4si4(x, iy, fptr);
}

vrs8_t
__gs_powi_8_p(vrs8_t x, vis8_t iy)
{
  float (*fptr)(float, int32_t);
  fptr = (float(*)(float, int32_t))MTH_DISPATCH_TBL[func_powi][sv_ss][frp_p];
  return __ZGVyN8vv__mth_i_vr4vi4(x, iy, fptr);
}

vrs8_t
__gs_powk1_8_p(vrs8_t x, long long iy)
{
  float (*fptr)(float, long long);
  fptr = (float(*)(float, long long))MTH_DISPATCH_TBL[func_powk1][sv_ss][frp_p];
  return __ZGVyN8v__mth_i_vr4si8(x, iy, fptr);
}

vrs8_t
__gs_powk_8_p(vrs8_t x, vid4_t iyu, vid4_t iyl)
{
  float (*fptr)(float, long long);
  fptr = (float(*)(float, long long))MTH_DISPATCH_TBL[func_powk][sv_ss][frp_p];
  return __ZGVyN8vv__mth_i_vr4vi8(x, iyu, iyl, fptr);
}

vrd4_t
__gd_powi1_4_r(vrd4_t x, int32_t iy)
{
  double (*fptr)(double, int32_t);
  fptr = (double(*)(double, int32_t))MTH_DISPATCH_TBL[func_powi1][sv_ds][frp_r];
  return __ZGVyN4v__mth_i_vr8si4(x, iy, fptr);
}

vrd4_t
__gd_powi_4_r(vrd4_t x, vis4_t iy)
{
  double (*fptr)(double, int32_t);
  fptr = (double(*)(double, int32_t))MTH_DISPATCH_TBL[func_powi][sv_ds][frp_r];
  return __ZGVyN4vv__mth_i_vr8vi4(x, iy, fptr);
}

vrd4_t
__gd_powk1_4_r(vrd4_t x, long long iy)
{
  double (*fptr)(double, long long);
  fptr = (double(*)(double, long long))MTH_DISPATCH_TBL[func_powk1][sv_ds][frp_r];
  return __ZGVyN4v__mth_i_vr8si8(x, iy, fptr);
}

vrd4_t
__gd_powk_4_r(vrd4_t x, vid4_t iy)
{
  double (*fptr)(double, long long);
  fptr = (double(*)(double, long long))MTH_DISPATCH_TBL[func_powk][sv_ds][frp_r];
  return __ZGVyN4vv__mth_i_vr8vi8(x, iy, fptr);
}

vrs8_t
__gs_powi1_8_r(vrs8_t x, int32_t iy)
{
  float (*fptr)(float, int32_t);
  fptr = (float(*)(float, int32_t))MTH_DISPATCH_TBL[func_powi1][sv_ss][frp_r];
  return __ZGVyN8v__mth_i_vr4si4(x, iy, fptr);
}

vrs8_t
__gs_powi_8_r(vrs8_t x, vis8_t iy)
{
  float (*fptr)(float, int32_t);
  fptr = (float(*)(float, int32_t))MTH_DISPATCH_TBL[func_powi][sv_ss][frp_r];
  return __ZGVyN8vv__mth_i_vr4vi4(x, iy, fptr);
}

vrs8_t
__gs_powk1_8_r(vrs8_t x, long long iy)
{
  float (*fptr)(float, long long);
  fptr = (float(*)(float, long long))MTH_DISPATCH_TBL[func_powk1][sv_ss][frp_r];
  return __ZGVyN8v__mth_i_vr4si8(x, iy, fptr);
}

vrs8_t
__gs_powk_8_r(vrs8_t x, vid4_t iyu, vid4_t iyl)
{
  float (*fptr)(float, long long);
  fptr = (float(*)(float, long long))MTH_DISPATCH_TBL[func_powk][sv_ss][frp_r];
  return __ZGVyN8vv__mth_i_vr4vi8(x, iyu, iyl, fptr);
}
